### ISSUE TITLE
Add support for "remember-me" functionality

### ISSUE THREAD

**Issue by apetrovnsip** [vaadin/vaadin-login-flow#81] opened 2019-10-30 14:04 UTC
It would be helpful to include a "Remember me" checkbox which would allow for login info to be stored for a period of time.

**Comment by web-padawan** [comment] 2020-02-21 20:12
Closing as duplicate of vaadin/vaadin-login#87 which is a feature request in the web component.

**Closed by web-padawan** 2020-02-21 20:12 UTC
